# Generated by Django 5.0.2 on 2024-04-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraProtocols',
            fields=[
                ('protocol', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CameraProtocols',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('camera_ip', models.CharField(max_length=100)),
                ('camera_auth', models.BooleanField()),
                ('camera_username', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_password', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_stream_path', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_port_no', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_exist', models.BooleanField(blank=True, default=True, null=True)),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('protocol', models.ForeignKey(db_column='protocol', on_delete=django.db.models.deletion.DO_NOTHING, related_name='list_cameras', to='cameras.cameraprotocols')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_camera', to='recipients.recipients')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='list_cameras', to='cameras.locations')),
            ],
            options={
                'db_table': 'Cameras',
            },
        ),
    ]
