# Generated by Django 5.0.2 on 2024-04-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accidents', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidents',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nearby_accidents', to='cameras.cameras'),
        ),
        migrations.AddField(
            model_name='accidents',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cameras.locations'),
        ),
        migrations.AddField(
            model_name='accidents',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listed_accidents', to='accidents.severity'),
        ),
    ]
