# Generated by Django 5.0.2 on 2024-04-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Recipients',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(blank=True, null=True)),
                ('message_status', models.TextField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Falied')], null=True)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accident_messages', to='accidents.accidents')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to='recipients.recipients')),
            ],
            options={
                'db_table': 'MessageLog',
            },
        ),
    ]
